### ISSUE TITLE
Infra - Banco de Dados

### ISSUE THREAD

**Issue by diamarals** [GabrielPaliari/pomus#2]
- [x] Criar a conta na amazon (RDS)
- [x] Criar o banco de dados e uma tabela de teste
- [x] Testar um select remoto por linha de comando
- [x] Rodar um arquivo através do node no servidor que realize a conexão com o banco e mostre no browser do client o resultado da query

**Comment by JoSuzuki** [comment]
Sugestões do professor:
- Django
- Flask

**Comment by GabrielPaliari** [comment]
Foram criadas duas instâncias na amazon AWS: uma para o servidor e outra para o banco de dados. As informações de como conectar às máquinas estão no Drive do projeto, no arquivo: AWS/Formas de acesso. 
A instância de banco de dados está com o mySQL e o servidor foi programado com o nodejs. 
O próximo passo é criar uma RESTful API usando o EXPRESS juntamente com  o Express Generator. A função dessa API será tratar as funções de get, put, post e delete, mapeando-as corretamente para queries de CRUD no banco e retornando para o client ou inserindo na pase de dados os dados requisitados ou enviados.
